apiVersion: v1
kind: Service
metadata:
  name: catalogapi-np-srv
spec:
  type: NodePort
  selector:
    app: catalogapi
  ports:
    - name: catalogapi
      protocol: TCP
      port: 80
      targetPort: 80